"""add telegram_link_token to users

Revision ID: bbd50dada2c6
Revises: e5b394a535e0
Create Date: 2026-09-17 12:51:51.798502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbd50dada2c6'
down_revision: Union[str, None] = 'e5b394a535e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_link_token', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_telegram_link_token'), 'users', ['telegram_link_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_telegram_link_token'), table_name='users')
    op.drop_column('users', 'telegram_link_token')
    # ### end Alembic commands ###
